# Change these first
owner: tjsky # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 反代1（diii.tk）
    url: https://diii.tk/https://1.1.1.1/cdn-cgi/trace
  - name: 反代2（go-back.cf）
    url: https://api-pikpak.go-back.cf/https://1.1.1.1/cdn-cgi/trace
  - name: 反代3（tjsky.cf）
    url: https://api-pikpak.tjsky.cf/https://1.1.1.1/cdn-cgi/trace
  - name: 反代4（tjsky-1.cf）
    url: https://api-pikpak.tjsky-1.cf/https://1.1.1.1/cdn-cgi/trace

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tjsky/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
